[workspace]
members = ["examples/*", "uniform"]
resolver = "2"

default-members = ["uniform"]

[workspace.package]
rust-version = "1.86.0"
version = "0.2.0"
edition = "2024"
authors = ["Fero Forgac <4gac@users.noreply.github.com>"]
