[package]
name = "corporum"
version = "0.1.0"
edition = "2021"
authors = ["Fero Forgac <fero4gac@protonmail.com>"]

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
rmp-serde = "1.1.1"
rmp = "^0.8"
serde_json = "1.0.91"
serde-pickle = "1.0"
serde_cbor = "0.11.2"
