[package]
name = "uniform"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0.26"
thiserror = "2.0.11"
